### PR TITLE
cli: reindex ignores deleted records

### LINKED ISSUE #55: cli: reindex does not take deleted pid into account
The reindex command assumes that all records in the database can be indexed. This assumption works only for simple usage, and doesn't cover e.g. cases where you have a deleted persistent identifier with non-deleted record (e.g. to store a removal reason).

Also, reindex command does not remove records from the index which no longer exists in the database, hence it possibly won't bring your index into sync with your database, which is usually what you would need the command to do.

### PR DESCRIPTION
**Pull request by switowski**
* Reindex command now won't index deleted records (records without PID)
  (closes #55).

### CODE REVIEW

**Comment by switowski** [comment]
I will add the possibility to reindex only given records in the new commit.

**Comment by switowski** [comment]
Added the PID type as a required parameter. It means that the code that runs `reindex` without the `pid-type` parameter will now fail. @lnielsen should we add a warning somewhere (it the code/in the release notes as a breaking change)?

**Comment by lnielsen** [comment]
Hmmm.....I think it's mainly invenio documentation that has to be updated.....

**Comment by lnielsen** [comment]
Ups....didn't mean to close the PR...

**Comment by switowski** [comment]
If you could point me to which part of the documentation contains this information, I will update it (searching for `reindex` in https://invenio-indexer.readthedocs.io/en/latest/ doesn't return anything).

**Comment by lnielsen** [comment]
Sorry, I meant from the general docs: http://invenio.readthedocs.io/en/iugw2017/usersguide/tutorial/index.html but I'm not sure where....I think there's likely also some scripts, but I would just merge this one as I anyway have to take a pass over the documentation.

**Comment by switowski** [comment]
Ok, then this PR is just waiting for the :green_heart: and it can be merged.

**Pull request merged**
