### PR TITLE
api: created/updated indexing

### PR DESCRIPTION
**Pull request by lnielsen**
* Adds record created/updated timestamps to all indexed records.

Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>

### CODE REVIEW

**Comment by jmartinm** [comment]
What version of `flower` do you have?

I am getting:

```
pkg_resources.ContextualVersionConflict Requirement.parse('pytz==2015.7'), set(['flower']))
```

**Comment by lnielsen** [comment]
@jmartinm Does if you run ``pip install flower --upgrade``?

**Comment by jmartinm** [comment]
Yes, then it works fine. Was just wondering if we have the correct dependency versions set so that other people don't get the same conflict.

**Comment by lnielsen** [comment]
I think this usually happens when you've been using your virtual env for some time....

**Comment by jmartinm** [comment]
Might be, my `venv` has been around for a long time indeed.

**Comment by jmartinm** [comment]
Apart from that 👍 Tested it and works for me.

**Pull request merged**
