### PR TITLE
global: release checklist

### PR DESCRIPTION
**Pull request by PaulinaLach**
* FIX Adds changes according to release preparation checklist.

Signed-off-by: Paulina Lach <paulina.malgorzata.lach@cern.ch>

### CODE REVIEW

**Comment by diegodelemos** [comment]
`index run` command is not being properly displayed by Sphinx:
http://invenio-indexer.readthedocs.io/en/latest/usage.html#bulk-indexing
There is an extra colon in  https://github.com/inveniosoftware/invenio-indexer/blob/master/invenio_indexer/__init__.py#L111

**Comment by diegodelemos** [comment]
Currently there is no documentation for [`invenio_indexer.api.Producer`](http://invenio-indexer.readthedocs.io/en/latest/api.html#invenio_indexer.api.Producer) parameters. From a reader point of view it seems weird, WDYT about using `intersphinx` to point to [`kombu.Producer`](http://kombu.readthedocs.io/en/latest/_modules/kombu/messaging.html#Producer) docs with something like follows:
```
More info can be found here  :class:`kombu:kombu.Producer`
```

**Comment by diegodelemos** [comment]
Celery tasks are not currently autodocumented by `Sphinx` (see [here](http://invenio-indexer.readthedocs.io/en/latest/api.html#module-invenio_indexer.tasks)). There is an [official way](http://docs.celeryproject.org/en/latest/reference/celery.contrib.sphinx.html) to have them retrieved by `Sphinx`.

**Comment by lnielsen** [comment]
@diegodelemos Thanks for the doing a good review. I might be best if you can create new issues for the identified problems as @PaulinaLach is finishing up, and also looks like most of them could be good small starter tasks for you and Harri :-)

**Pull request merged**
